<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirm Account</title>
    <link rel="stylesheet" href="/static/css/auth/auth.css">
    <link rel="icon" href="/static/files/assets/favicon.ico" type="image/x-icon">
</head>
<body>
<#include "components/navbar.ftlh">
<div class="container">
        <div class="content-container">
            <h2 class="confirm-font">Confirm Your Account</h2>
            <p class="confirm-font">Please check your email and follow the instructions to confirm your account.</p>
        </div>
    </div>

<#include "components/footer.ftlh">
</body>
</html>
