<footer>
    <div class="container">
        <div class="footer-info">
            <h3 style="font-weight: bold;">Euphoria</h3>
            <p>The Destination Where Music Ignites the Soul and Elevates the Spirit</p>
        </div>
        <div class="footer-rights">
            <p>&copy; 2024 Euphoria. All rights reserved.</p>
        </div>
    </div>
</footer>
<link rel="stylesheet" href="/static/css/components/footer.css">
