<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="/static/css/home/index.css">
    <link rel="icon" href="/static/files/assets/favicon.ico" type="image/x-icon">
</head>

<body>

<#include "components/navbar.ftlh">

<div class="decode-text">
    <div class="text-animation">E</div>
    <div class="text-animation">U</div>
    <div class="text-animation">P</div>
    <div class="text-animation">H</div>
    <div class="text-animation">O</div>
    <div class="text-animation">R</div>
    <div class="text-animation">I</div>
    <div class="text-animation">A</div>
    <div class="slogan">L e t &nbsp; t h e &nbsp; M u s i c &nbsp; T a k e &nbsp; Y o u &nbsp; H i g h e r</div>
</div>

<script src="/static/js/index.js"></script>
</body>
</html>
